# Generated by Django 5.0.6 on 2024-07-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=50, null=True, verbose_name='Место')),
                ('time', models.TimeField(verbose_name='Время')),
                ('action', models.CharField(max_length=50, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Хорошая привычка')),
                ('periodicity', models.IntegerField(default=1, verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=50, null=True, verbose_name='Бонус')),
                ('duration', models.DurationField(blank=True, default=None, null=True, verbose_name='Продолжительность')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
